[build]
  command = "pnpm add -g @mintlify/cli@latest && mintlify build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "20.11.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200